# Generated by Django 3.1.5 on 2021-01-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('iq', models.IntegerField()),
                ('ha', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
